<GridLayout>:
GridLayout:
    cols: 1
    rows: 4
    size_hint_y: 1

    GridLayout:
        cols: 1
        rows: 1
        size_hint_y: 0.06

        Button:
            text: "Zurück"
    
    GridLayout:
        cols: 1
        rows: 2
        size_hint_y: 0.5

        Label:
            text: "Ersteller: Daniel, Florian, Katja"

        Label:
            text: "App-Version: 1.0"

    GridLayout:
        cols: 1
        rows: 1
        size_hint_y: 0.5
