MDScreenManager:
    id: screen_manager
    MDScreen:
        md_bg_color: "#000000"
        name: "main"

        MDHeroFrom:
            id: hero_from
            tag: "hero"

            MDIconButton:
                opacity: 0.0
                disabled: True

        MDGridLayout:
            cols: 1
            rows: 3
            size_hint_y: 1
            id: titleGrid

            MDGridLayout:
                cols: 3
                rows: 1
                size_hint_y: 0.08
                id: title_grid

                MDIconButton:
                    id: info_button
                    icon: "information"
                    md_bg_color: "#5780FF"
                    on_release:
                        root.current_heroes = ["hero"]
                        root.current = "info"
            
                MDLabel:           
                    text: "Ankeralarm"
                    halign: "center"
                    valign: "top"
                    md_bg_color: "#5780FF"
                    #adaptive_height: True
                    text_size: root.width, root.height
                    font_size: 32

                MDIconButton:
                    icon: "file-settings"
                    md_bg_color: "#5780FF"
                    on_press: app.Stop_Update_Circle()
                    on_release:
                        root.current_heroes = ["hero"]
                        root.current = "settings"

            MapView:
                id: mapview
                lat: 48.4715279
                lon: 7.9512879
                zoom: 16
                size_hint_y: 0.6
                pos_hint_y: 0.9
            

            MDGridLayout:
                cols: 2
                rows: 1
                size_hint_y: 0.25

                MyToggleButton:
                    id: launchButton
                    group: "toggle_group"
                    md_bg_color: "#5780FF"
                    text: "Start"
                    size_hint_x: 1
                    size_hint_y: 1
                    halign: "center"
                    font_color_normal:  1,  1,  1,  1  # Rote Farbe im normalen Zustand
                    font_color_down:  1,  1,  1,  1  # Grüne Farbe im gedrückten Zustand
                    on_release: app.drawCircle()
                
                MDGridLayout:
                    cols: 3
                    rows: 3

                    MDIconButton:
                        md_bg_color: "#5780FF"
                        size_hint_x: 1
                        size_hint_y: 1
                        disabled: True
                        opacity: 0.0
                    MDIconButton:
                        md_bg_color: "#5780FF"
                        size_hint_x: 1
                        size_hint_y: 1
                        on_press: app.MoveAnchor()
                    MDIconButton:
                        md_bg_color: "#5780FF"
                        size_hint_x: 1
                        size_hint_y: 1
                        disabled: True
                        opacity: 0.0
                    MDIconButton:
                        md_bg_color: "#5780FF"
                        size_hint_x: 1
                        size_hint_y: 1
                    MDIconButton:
                        md_bg_color: "#FFFFFF"
                        size_hint_x: 1
                        size_hint_y: 1
                        on_press: app.centerMap()
                    MDIconButton:
                        md_bg_color: "#5780FF"
                        size_hint_x: 1
                        size_hint_y: 1
                    MDIconButton:
                        md_bg_color: "#5780FF"
                        size_hint_x: 1
                        size_hint_y: 1
                        disabled: True
                        opacity: 0.0
                    MDIconButton:
                        md_bg_color: "#5780FF"
                        size_hint_x: 1
                        size_hint_y: 1
                    MDIconButton:
                        md_bg_color: "#5780FF"
                        size_hint_x: 1
                        size_hint_y: 1
                        disabled: True
                        opacity: 0.0


    MDScreen:
        name: "settings"
        hero_to: hero_to

        MDHeroTo:
            id: hero_to
            tag: "hero"

            MDIconButton:
                opacity: 0.0
                disabled: True

        MDGridLayout:
            cols: 1
            rows: 5
            size_hint_y: 1

            MDGridLayout:
                cols: 2
                rows: 1
                size_hint_y: 0.15

                MDIconButton:
                    icon:"arrow-left"
                    md_bg_color: "#8470ff"
                    size_hint:0.1,0.1
                    on_release:
                        root.current_heroes = ["hero"]
                        root.current = "main"
                        app.drawCircle()

                MDLabel:
                    text: "Einstellungen"
                    halign: "center"
                    valign: "top"
                    md_bg_color: "#8470ff"
                    font_size: 32
                    size_hint: 1, 1

            MDGridLayout:
                cols:3
                rows:1       
                size_hint_y: 0.4
                padding: [20,20]

                # MDLabel:
                #     text: 'Radius'
                #     halign: "left"
                #     valign: "middle"
                #     text_size: root.width, root.height
                #     font_size: 25

                MDTextField:
                    id: radius
                    mode: "fill"
                    hint_text: "in Meter"
                    # helper_text: "Bitte den Radius in Meter eingeben"
                    helper_text_mode: "persistent"
                    halign:"center"
                    text: "200"
                    required: True
                    font_size: 38
                    input_filter: 'int'
                    size_hint: 1, 1
                    on_text: app.dateiSchreiben()

                MDIconButton:
                    icon: "plus"
                    valign: "center"
                    size_hint: 1, 1
                    on_press: app.radiuserhoehen()
                    on_release: app.dateiSchreiben()

                MDIconButton:
                    icon: "minus"
                    valign: "center"
                    size_hint: 1, 1
                    on_press: app.radiusverringern()
                    on_release: app.dateiSchreiben()                        

            MDGridLayout:
                rows: 1
                cols: 2
                size_hint_y: 0.3
                padding: [20,20]
                MDLabel:
                    text: 'Alarm Sound auswählen'
                    font_size: 25
                    halign: "left"
                    valign: "middle"
                    text_size: root.width, root.height

                Spinner:
                    id: sound_spinner
                    text: 'Sound'
                    values: ('Sound 1', 'Sound 2', 'Sound 3')
                    on_text: app.dateiSchreiben()

            MDGridLayout:
                rows:1
                cols:1
                size_hint_y: 0.15

            MDGridLayout:
                size_hint_:0.4
                
    
    MDScreen:
        name: "info"
        hero_to: hero_to_info

        MDHeroTo:
            id: hero_to_info
            tag: "hero"

            MDIconButton:
                opacity: 0.0
                disabled: True

        MDGridLayout:
            cols: 1
            rows: 2
            size_hint_y: 1

            MDGridLayout:
                cols: 1
                rows: 2
                size_hint_y: 0.2

                MDLabel:
                    #color: 1,1,1,1
                    text: "Ersteller: Daniel, Florian, Katja"
                    valign: 'center'
                    halign: 'center'

                MDLabel:
                    #color:1,1,1,1
                    text: "App-Version: 1.0"
                    valign: 'center'
                    halign: 'center'

            MDGridLayout:
                cols: 1
                rows: 1
                size_hint_y: 0.5

                Button:
                    text: "Zurück"
                    on_release:
                        root.current_heroes = ["hero"]
                        root.current = "main" 
    

                    